<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Salvo.Elevator</RootNamespace>
    <AssemblyName>Salvo.Elevator</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Salvo.Core\Salvo.Core.csproj" />
  </ItemGroup>
</Project>
