// <auto-generated />
// Strongly-typed accessor for Strings.resx. Regenerate via `Update-Resx` or keep in sync by hand.
#nullable enable

using System.Globalization;
using System.Resources;

namespace StartupGroups.App.Resources;

public static class Strings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("StartupGroups.App.Resources.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? $"[[{name}]]";

    // Window titles
    public static string Window_Main_Title => Get(nameof(Window_Main_Title));
    public static string Window_AddApp_Title => Get(nameof(Window_AddApp_Title));
    public static string Window_Group_Title => Get(nameof(Window_Group_Title));
    public static string Window_App_Title => Get(nameof(Window_App_Title));
    public static string Window_RegistryEditor_Title => Get(nameof(Window_RegistryEditor_Title));

    // Sidebar
    public static string Sidebar_Groups_Heading => Get(nameof(Sidebar_Groups_Heading));
    public static string Sidebar_System_Heading => Get(nameof(Sidebar_System_Heading));
    public static string Sidebar_WindowsStartup_Label => Get(nameof(Sidebar_WindowsStartup_Label));

    // Common actions
    public static string Action_New => Get(nameof(Action_New));
    public static string Action_Add => Get(nameof(Action_Add));
    public static string Action_AddApp => Get(nameof(Action_AddApp));
    public static string Action_AddBlank => Get(nameof(Action_AddBlank));
    public static string Action_AddSelected => Get(nameof(Action_AddSelected));
    public static string Action_EditSelected => Get(nameof(Action_EditSelected));
    public static string Action_Save => Get(nameof(Action_Save));
    public static string Action_Cancel => Get(nameof(Action_Cancel));
    public static string Action_Yes => Get(nameof(Action_Yes));
    public static string Action_No => Get(nameof(Action_No));
    public static string Action_Ok => Get(nameof(Action_Ok));
    public static string Action_Browse => Get(nameof(Action_Browse));
    public static string Action_LaunchAll => Get(nameof(Action_LaunchAll));
    public static string Action_StopAll => Get(nameof(Action_StopAll));
    public static string Action_Launch => Get(nameof(Action_Launch));
    public static string Action_Stop => Get(nameof(Action_Stop));
    public static string Action_Edit => Get(nameof(Action_Edit));
    public static string Action_Remove => Get(nameof(Action_Remove));
    public static string Action_Refresh => Get(nameof(Action_Refresh));
    public static string Action_OpenLocation => Get(nameof(Action_OpenLocation));
    public static string Action_RenameGroup => Get(nameof(Action_RenameGroup));
    public static string Action_RemoveGroup => Get(nameof(Action_RemoveGroup));
    public static string Action_OpenConfigFolder => Get(nameof(Action_OpenConfigFolder));
    public static string Action_OpenLogFolder => Get(nameof(Action_OpenLogFolder));
    public static string Action_Logs => Get(nameof(Action_Logs));

    // Apps pane
    public static string Apps_Heading => Get(nameof(Apps_Heading));
    public static string Apps_NoGroupSelected => Get(nameof(Apps_NoGroupSelected));
    public static string Apps_CountFormat => Get(nameof(Apps_CountFormat));
    public static string Apps_Column_Actions => Get(nameof(Apps_Column_Actions));
    public static string ViewMode_Compact => Get(nameof(ViewMode_Compact));
    public static string ViewMode_Detailed => Get(nameof(ViewMode_Detailed));
    public static string Settings_Section_Diagnostics => Get(nameof(Settings_Section_Diagnostics));
    public static string Settings_ConfigFile_Label => Get(nameof(Settings_ConfigFile_Label));
    public static string Settings_LogFolder_Label => Get(nameof(Settings_LogFolder_Label));
    public static string Settings_LogFolder_Hint => Get(nameof(Settings_LogFolder_Hint));

    // Windows Startup
    public static string WinStartup_Description => Get(nameof(WinStartup_Description));
    public static string WinStartup_LaunchAtSignIn_Title => Get(nameof(WinStartup_LaunchAtSignIn_Title));
    public static string WinStartup_LaunchAtSignIn_Description => Get(nameof(WinStartup_LaunchAtSignIn_Description));
    public static string WinStartup_Column_Enabled => Get(nameof(WinStartup_Column_Enabled));
    public static string WinStartup_Column_Name => Get(nameof(WinStartup_Column_Name));
    public static string WinStartup_Column_Command => Get(nameof(WinStartup_Column_Command));
    public static string WinStartup_Column_Source => Get(nameof(WinStartup_Column_Source));
    public static string WinStartup_CountFormat => Get(nameof(WinStartup_CountFormat));
    public static string WinStartup_AddedFormat => Get(nameof(WinStartup_AddedFormat));
    public static string WinStartup_RemovedFormat => Get(nameof(WinStartup_RemovedFormat));
    public static string WinStartup_CannotModifyFormat => Get(nameof(WinStartup_CannotModifyFormat));
    public static string WinStartup_RequiresAdmin => Get(nameof(WinStartup_RequiresAdmin));
    public static string WinStartup_ToggleFailedFormat => Get(nameof(WinStartup_ToggleFailedFormat));
    public static string WinStartup_AddFailedFormat => Get(nameof(WinStartup_AddFailedFormat));
    public static string WinStartup_RemoveFailedFormat => Get(nameof(WinStartup_RemoveFailedFormat));
    public static string WinStartup_EditRegistryValue => Get(nameof(WinStartup_EditRegistryValue));

    // Dialogs
    public static string Dialog_DuplicateGroup_Title => Get(nameof(Dialog_DuplicateGroup_Title));
    public static string Dialog_DuplicateGroup_MessageFormat => Get(nameof(Dialog_DuplicateGroup_MessageFormat));
    public static string Dialog_RemoveGroup_Title => Get(nameof(Dialog_RemoveGroup_Title));
    public static string Dialog_RemoveGroup_MessageFormat => Get(nameof(Dialog_RemoveGroup_MessageFormat));
    public static string Dialog_RemoveApp_Title => Get(nameof(Dialog_RemoveApp_Title));
    public static string Dialog_RemoveApp_MessageFormat => Get(nameof(Dialog_RemoveApp_MessageFormat));
    public static string Dialog_RemoveStartupItem_Title => Get(nameof(Dialog_RemoveStartupItem_Title));
    public static string Dialog_RemoveStartupItem_MessageFormat => Get(nameof(Dialog_RemoveStartupItem_MessageFormat));
    public static string Dialog_Startup_Title => Get(nameof(Dialog_Startup_Title));
    public static string Dialog_AutoStart_Title => Get(nameof(Dialog_AutoStart_Title));
    public static string Dialog_AdministratorRequired_Title => Get(nameof(Dialog_AdministratorRequired_Title));
    public static string Dialog_AdministratorRequired_StartFormat => Get(nameof(Dialog_AdministratorRequired_StartFormat));
    public static string Dialog_AdministratorRequired_StopFormat => Get(nameof(Dialog_AdministratorRequired_StopFormat));
    public static string Dialog_UnexpectedErrorFormat => Get(nameof(Dialog_UnexpectedErrorFormat));

    // File / folder dialogs
    public static string FileDialog_SelectExecutable_Title => Get(nameof(FileDialog_SelectExecutable_Title));
    public static string FileDialog_SelectExecutable_Filter => Get(nameof(FileDialog_SelectExecutable_Filter));
    public static string FileDialog_SelectFolder_Title => Get(nameof(FileDialog_SelectFolder_Title));

    // Status
    public static string Status_Ready => Get(nameof(Status_Ready));
    public static string Status_LaunchingFormat => Get(nameof(Status_LaunchingFormat));
    public static string Status_StoppingFormat => Get(nameof(Status_StoppingFormat));
    public static string Status_AppResultFormat => Get(nameof(Status_AppResultFormat));
    public static string Status_AddedAppFormat => Get(nameof(Status_AddedAppFormat));
    public static string Status_AddedAppsFormat => Get(nameof(Status_AddedAppsFormat));
    public static string Status_ElevationFailed => Get(nameof(Status_ElevationFailed));
    public static string Status_GroupActionFormat => Get(nameof(Status_GroupActionFormat));
    public static string Status_GroupActionWithFailureFormat => Get(nameof(Status_GroupActionWithFailureFormat));
    public static string Status_VerbLaunch => Get(nameof(Status_VerbLaunch));
    public static string Status_VerbStop => Get(nameof(Status_VerbStop));

    // Add App picker
    public static string AddAppPicker_Heading => Get(nameof(AddAppPicker_Heading));
    public static string AddAppPicker_Subtitle => Get(nameof(AddAppPicker_Subtitle));
    public static string AddAppPicker_SearchPlaceholder => Get(nameof(AddAppPicker_SearchPlaceholder));
    public static string AddAppPicker_SelectedFormat => Get(nameof(AddAppPicker_SelectedFormat));
    public static string AddAppPicker_SourceStore => Get(nameof(AddAppPicker_SourceStore));
    public static string AddAppPicker_SourceDesktop => Get(nameof(AddAppPicker_SourceDesktop));
    public static string AddAppPicker_SourceService => Get(nameof(AddAppPicker_SourceService));
    public static string AddAppPicker_SourceShell => Get(nameof(AddAppPicker_SourceShell));
    public static string AddAppPicker_SourceScoop => Get(nameof(AddAppPicker_SourceScoop));

    // Group editor
    public static string GroupEditor_Heading => Get(nameof(GroupEditor_Heading));
    public static string GroupEditor_Id_Label => Get(nameof(GroupEditor_Id_Label));
    public static string GroupEditor_Name_Label => Get(nameof(GroupEditor_Name_Label));
    public static string GroupEditor_Icon_Label => Get(nameof(GroupEditor_Icon_Label));
    public static string GroupEditor_IconSearch_Placeholder => Get(nameof(GroupEditor_IconSearch_Placeholder));
    public static string GroupEditor_IconTab_Apps => Get(nameof(GroupEditor_IconTab_Apps));
    public static string GroupEditor_IconTab_Outline => Get(nameof(GroupEditor_IconTab_Outline));
    public static string GroupEditor_IconTab_Filled => Get(nameof(GroupEditor_IconTab_Filled));
    public static string GroupEditor_IconTab_Windows => Get(nameof(GroupEditor_IconTab_Windows));

    // App editor
    public static string AppEditor_Heading => Get(nameof(AppEditor_Heading));
    public static string AppEditor_Name_Label => Get(nameof(AppEditor_Name_Label));
    public static string AppEditor_Kind_Label => Get(nameof(AppEditor_Kind_Label));
    public static string AppEditor_Target_Label => Get(nameof(AppEditor_Target_Label));
    public static string AppEditor_Arguments_Label => Get(nameof(AppEditor_Arguments_Label));
    public static string AppEditor_SuggestedArguments_Label => Get(nameof(AppEditor_SuggestedArguments_Label));
    public static string AppEditor_WorkingDir_Label => Get(nameof(AppEditor_WorkingDir_Label));
    public static string AppEditor_Service_Label => Get(nameof(AppEditor_Service_Label));
    public static string AppEditor_Delay_Label => Get(nameof(AppEditor_Delay_Label));
    public static string AppEditor_Enabled_Label => Get(nameof(AppEditor_Enabled_Label));

    // Registry editor
    public static string RegEditor_Heading => Get(nameof(RegEditor_Heading));
    public static string RegEditor_KeyPath_Label => Get(nameof(RegEditor_KeyPath_Label));
    public static string RegEditor_CopyKeyPath_Tooltip => Get(nameof(RegEditor_CopyKeyPath_Tooltip));
    public static string RegEditor_OpenInRegedit_Tooltip => Get(nameof(RegEditor_OpenInRegedit_Tooltip));
    public static string RegEditor_OpenInRegeditFailedFormat => Get(nameof(RegEditor_OpenInRegeditFailedFormat));
    public static string RegEditor_KeyPathCopied => Get(nameof(RegEditor_KeyPathCopied));
    public static string RegEditor_ValueName_Label => Get(nameof(RegEditor_ValueName_Label));
    public static string RegEditor_ValueData_Label => Get(nameof(RegEditor_ValueData_Label));
    public static string RegEditor_Path_Label => Get(nameof(RegEditor_Path_Label));
    public static string RegEditor_Arguments_Label => Get(nameof(RegEditor_Arguments_Label));
    public static string RegEditor_RawMode_Hint => Get(nameof(RegEditor_RawMode_Hint));
    public static string RegEditor_Type_Label => Get(nameof(RegEditor_Type_Label));
    public static string RegEditor_Type_String => Get(nameof(RegEditor_Type_String));
    public static string RegEditor_Type_ExpandString => Get(nameof(RegEditor_Type_ExpandString));
    public static string RegEditor_RequiresAdmin_Hint => Get(nameof(RegEditor_RequiresAdmin_Hint));
    public static string RegEditor_NameRequired => Get(nameof(RegEditor_NameRequired));
    public static string RegEditor_CommandRequired => Get(nameof(RegEditor_CommandRequired));
    public static string RegEditor_NameConflictFormat => Get(nameof(RegEditor_NameConflictFormat));
    public static string RegEditor_SaveFailedFormat => Get(nameof(RegEditor_SaveFailedFormat));
    public static string RegEditor_ElevationDeclined => Get(nameof(RegEditor_ElevationDeclined));
    public static string RegEditor_Saved => Get(nameof(RegEditor_Saved));
    public static string RegEditor_ReadFailed => Get(nameof(RegEditor_ReadFailed));

    // Running state
    public static string RunningState_Running => Get(nameof(RunningState_Running));
    public static string RunningState_Stopped => Get(nameof(RunningState_Stopped));

    // Tray menu
    public static string Tray_Tooltip => Get(nameof(Tray_Tooltip));
    public static string Tray_OpenMain => Get(nameof(Tray_OpenMain));
    public static string Tray_Exit => Get(nameof(Tray_Exit));

    // Settings
    public static string Sidebar_Settings_Label => Get(nameof(Sidebar_Settings_Label));
    public static string Settings_Heading => Get(nameof(Settings_Heading));
    public static string Settings_Subtitle => Get(nameof(Settings_Subtitle));
    public static string Settings_Section_Appearance => Get(nameof(Settings_Section_Appearance));
    public static string Settings_Section_Behavior => Get(nameof(Settings_Section_Behavior));
    public static string Settings_Section_About => Get(nameof(Settings_Section_About));
    public static string Settings_Theme_Label => Get(nameof(Settings_Theme_Label));
    public static string Settings_Theme_Hint => Get(nameof(Settings_Theme_Hint));
    public static string Settings_Theme_System => Get(nameof(Settings_Theme_System));
    public static string Settings_Theme_Light => Get(nameof(Settings_Theme_Light));
    public static string Settings_Theme_Dark => Get(nameof(Settings_Theme_Dark));
    public static string Settings_Theme_OpenWindowsColors => Get(nameof(Settings_Theme_OpenWindowsColors));
    public static string Settings_AutoStart_OpenTaskScheduler => Get(nameof(Settings_AutoStart_OpenTaskScheduler));
    public static string Settings_Language_ReportIssue => Get(nameof(Settings_Language_ReportIssue));
    public static string Settings_Language_Label => Get(nameof(Settings_Language_Label));
    public static string Settings_Language_Hint => Get(nameof(Settings_Language_Hint));
    public static string Settings_MinimizeToTray_Label => Get(nameof(Settings_MinimizeToTray_Label));
    public static string Settings_MinimizeToTray_Hint => Get(nameof(Settings_MinimizeToTray_Hint));
    public static string Settings_Notifications_Label => Get(nameof(Settings_Notifications_Label));
    public static string Settings_Notifications_Hint => Get(nameof(Settings_Notifications_Hint));
    public static string Settings_AutoStart_Label => Get(nameof(Settings_AutoStart_Label));
    public static string Settings_AutoStart_Hint => Get(nameof(Settings_AutoStart_Hint));
    public static string Settings_About_VersionFormat => Get(nameof(Settings_About_VersionFormat));
    public static string Settings_About_OpenGitHub => Get(nameof(Settings_About_OpenGitHub));

    // Version & updates
    public static string Settings_Section_Updates => Get(nameof(Settings_Section_Updates));
    public static string Settings_Version_ReleaseNotes => Get(nameof(Settings_Version_ReleaseNotes));
    public static string Settings_Version_LastCheckedFormat => Get(nameof(Settings_Version_LastCheckedFormat));
    public static string Settings_Version_CheckNow => Get(nameof(Settings_Version_CheckNow));
    public static string Settings_Version_Checking => Get(nameof(Settings_Version_Checking));
    public static string Settings_Version_UpToDate => Get(nameof(Settings_Version_UpToDate));
    public static string Settings_Version_UpdateAvailable => Get(nameof(Settings_Version_UpdateAvailable));
    public static string Settings_Version_InstallNow => Get(nameof(Settings_Version_InstallNow));
    public static string Settings_Version_SeeWhatsNew => Get(nameof(Settings_Version_SeeWhatsNew));

    // Tooltips
    public static string Tooltip_OpenConfigFolder => Get(nameof(Tooltip_OpenConfigFolder));
    public static string Tooltip_OpenLogFolder => Get(nameof(Tooltip_OpenLogFolder));

    // Empty states
    public static string Empty_NoAppsInGroup_Title => Get(nameof(Empty_NoAppsInGroup_Title));
    public static string Empty_NoAppsInGroup_Hint => Get(nameof(Empty_NoAppsInGroup_Hint));
    public static string Empty_NoAppIcons_Title => Get(nameof(Empty_NoAppIcons_Title));
    public static string Empty_NoAppIcons_Hint => Get(nameof(Empty_NoAppIcons_Hint));
    public static string Empty_NoStartupItems_Title => Get(nameof(Empty_NoStartupItems_Title));
    public static string Empty_NoStartupItems_Hint => Get(nameof(Empty_NoStartupItems_Hint));

    // Admin status / pill
    public static string Admin_Pill_Recommended => Get(nameof(Admin_Pill_Recommended));
    public static string Admin_Pill_Active => Get(nameof(Admin_Pill_Active));
    public static string Admin_Status_Running => Get(nameof(Admin_Status_Running));
    public static string Admin_Status_Standard => Get(nameof(Admin_Status_Standard));

    // Elevation banner
    public static string ElevationBanner_ToggleDetailsTooltip => Get(nameof(ElevationBanner_ToggleDetailsTooltip));
    public static string ElevationBanner_Heading => Get(nameof(ElevationBanner_Heading));
    public static string ElevationBanner_RestartAsAdmin => Get(nameof(ElevationBanner_RestartAsAdmin));
    public static string ElevationBanner_DismissTooltip => Get(nameof(ElevationBanner_DismissTooltip));
    public static string ElevationBanner_Intro => Get(nameof(ElevationBanner_Intro));
    public static string ElevationBanner_SilentService_Heading => Get(nameof(ElevationBanner_SilentService_Heading));
    public static string ElevationBanner_SilentService_Body => Get(nameof(ElevationBanner_SilentService_Body));
    public static string ElevationBanner_Etw_Heading => Get(nameof(ElevationBanner_Etw_Heading));
    public static string ElevationBanner_Etw_Body => Get(nameof(ElevationBanner_Etw_Body));
    public static string ElevationBanner_SystemStartup_Heading => Get(nameof(ElevationBanner_SystemStartup_Heading));
    public static string ElevationBanner_SystemStartup_Body => Get(nameof(ElevationBanner_SystemStartup_Body));
    public static string ElevationBanner_ElevatedApps_Heading => Get(nameof(ElevationBanner_ElevatedApps_Heading));
    public static string ElevationBanner_ElevatedApps_Body => Get(nameof(ElevationBanner_ElevatedApps_Body));

    // Sidebar (continued)
    public static string Sidebar_Benchmarks_Label => Get(nameof(Sidebar_Benchmarks_Label));

    // Benchmarks page
    public static string Benchmarks_Heading => Get(nameof(Benchmarks_Heading));
    public static string Benchmarks_Subtitle => Get(nameof(Benchmarks_Subtitle));
    public static string Benchmarks_Metric_TotalLaunches => Get(nameof(Benchmarks_Metric_TotalLaunches));
    public static string Benchmarks_Metric_Ready => Get(nameof(Benchmarks_Metric_Ready));
    public static string Benchmarks_Metric_TimedOut => Get(nameof(Benchmarks_Metric_TimedOut));
    public static string Benchmarks_Metric_ColdMedian => Get(nameof(Benchmarks_Metric_ColdMedian));
    public static string Benchmarks_Metric_WarmMedian => Get(nameof(Benchmarks_Metric_WarmMedian));
    public static string Benchmarks_Section_PerApp => Get(nameof(Benchmarks_Section_PerApp));
    public static string Benchmarks_Metric_Last => Get(nameof(Benchmarks_Metric_Last));
    public static string Benchmarks_Metric_Median => Get(nameof(Benchmarks_Metric_Median));
    public static string Benchmarks_Metric_ColdMed => Get(nameof(Benchmarks_Metric_ColdMed));
    public static string Benchmarks_Metric_WarmMed => Get(nameof(Benchmarks_Metric_WarmMed));
    public static string Benchmarks_Section_SuggestedOrder => Get(nameof(Benchmarks_Section_SuggestedOrder));
    public static string Benchmarks_SuggestedOrder_Hint => Get(nameof(Benchmarks_SuggestedOrder_Hint));
    public static string Benchmarks_Hint_GroupLabel => Get(nameof(Benchmarks_Hint_GroupLabel));
    public static string Benchmarks_Hint_CurrentLabel => Get(nameof(Benchmarks_Hint_CurrentLabel));
    public static string Benchmarks_Hint_SuggestedLabel => Get(nameof(Benchmarks_Hint_SuggestedLabel));
    public static string Benchmarks_Hint_ApplyButton => Get(nameof(Benchmarks_Hint_ApplyButton));
    public static string Benchmarks_Section_GroupRuns => Get(nameof(Benchmarks_Section_GroupRuns));
    public static string Benchmarks_Metric_Total => Get(nameof(Benchmarks_Metric_Total));
    public static string Benchmarks_Metric_Bottleneck => Get(nameof(Benchmarks_Metric_Bottleneck));
    public static string Benchmarks_Section_RecentLaunches => Get(nameof(Benchmarks_Section_RecentLaunches));
    public static string Benchmarks_Regression_Tooltip => Get(nameof(Benchmarks_Regression_Tooltip));

    // Settings page: administrator mode
    public static string Settings_Section_AdminMode => Get(nameof(Settings_Section_AdminMode));
    public static string Settings_AdminMode_Description => Get(nameof(Settings_AdminMode_Description));
    public static string Settings_AdminMode_RestartAsAdmin => Get(nameof(Settings_AdminMode_RestartAsAdmin));
    public static string Settings_AdminMode_AlwaysRunLabel => Get(nameof(Settings_AdminMode_AlwaysRunLabel));
    public static string Settings_AdminMode_AlwaysRunHint_NeedsAdmin => Get(nameof(Settings_AdminMode_AlwaysRunHint_NeedsAdmin));
    public static string Settings_AdminMode_AlwaysRunHint_Active => Get(nameof(Settings_AdminMode_AlwaysRunHint_Active));
    public static string Settings_AdminMode_WarnLabel => Get(nameof(Settings_AdminMode_WarnLabel));
    public static string Settings_AdminMode_WarnHint => Get(nameof(Settings_AdminMode_WarnHint));
}
